version: '3.8'

services:
  #################################################
  # 1) PostgreSQL Database
  #################################################
  database:
    container_name: backend-database
    image: postgres:14.1
    environment:
      POSTGRES_USER: ms-service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres:/data/postgres
    ports:
      - "5332:5432"   # Host port 5332 -> Container port 5432
    networks:
      - database
    restart: unless-stopped

  #################################################
  # 2) Demo App (Pull from Docker Hub)
  #################################################
  demo-app:
    image: med3744lemin/demo-app:latest
    container_name: demo-app
    hostname: demo-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/demo_db
      SPRING_DATASOURCE_USERNAME: ms-service
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - database
      - monitoring
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  # Enables Watchtower monitoring for this container

  #################################################
  # 3) Prometheus
  #################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - demo-app

  #################################################
  # 4) Grafana
  #################################################
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

  #################################################
  # 5) Zipkin
  #################################################
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - monitoring

  #################################################
  # 6) Loki
  #################################################
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    volumes:
      - ./src/main/resources/loki-config.yml:/etc/loki/config.yml:ro
      - ./volumes/loki:/data/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  #################################################
  # 7) Promtail
  #################################################
  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - ./src/main/resources/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  #################################################
  # 8) Watchtower
  #################################################
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"  # Automatically remove old images
      WATCHTOWER_LABEL_ENABLE: "true"  # Only update containers with the Watchtower label
    networks:
      - monitoring  # Optional network; Watchtower needs access to Docker
    restart: unless-stopped


#################################################
# Networks
#################################################
networks:
  database:
    driver: bridge
  monitoring:
    driver: bridge

#################################################
# Volumes
#################################################
volumes:
  postgres:
  loki:
