server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ms-service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30m
  security:
    basic:
      enabled: false
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics,loggers,httptrace
      security:
        enabled: false
  health:
    show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      content-type: application/openmetrics-text  # Ensures correct content type

logging:
  level:
    root: INFO
    io.micrometer: DEBUG  # To monitor Micrometer-related logs

sleuth:
  sampler:
    probability: 1.0  # Trace 100% of requests (reduce in production for better performance)



micrometer:
  metrics:
    export:
      prometheus:
        enabled: true  # Ensures Prometheus metrics are exposed

logging.file:
  name: ./logs/app.log  # Specify log file location

loki:
  enabled: true  # Optional Loki configuration if needed

backup:
  path: ./backups

docker:
  container:
    name: postgres-db

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000  # 7 days
