server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ms-service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30m

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics,loggers,httptrace
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: demo-app
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    io.micrometer: DEBUG
  file:
    name: ./logs/app.log

micrometer:
  observation:
    enabled: true
  tracing:
    enabled: true

loki:
  enabled: true

backup:
  path: ./backups

docker:
  container:
    name: postgres-db

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000