server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    shared_store: filesystem
    cache_location: /data/loki/cache

  filesystem:
    directory: /data/loki/chunks

limits_config:
  retention_period: 168h
