global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'demo-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo-app:8080']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
