name: Build, Test, and Publish Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1) Build and Test Job (with Postgres as a service)
  build_and_test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:14.1
        env:
          POSTGRES_USER: ms-service
          POSTGRES_PASSWORD: password
          POSTGRES_DB: demo_db
        ports:
          - 5432:5432  # Exposes container port 5432 on host port 5432
        options: >-
          --health-cmd="pg_isready -U ms-service -d demo_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Wait a bit for Postgres container to be healthy
      - name: Wait for Postgres
        run: |
          echo "Sleeping 30s to ensure DB is ready..."
          sleep 30

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

  # 2) Build and Publish Docker Image Job
  build_and_publish:
    runs-on: ubuntu-latest

    # Only run if the above build_and_test job succeeded
    needs: [build_and_test]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean package

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t med3744lemin/demo-app:latest .

      - name: Push Docker image
        run: |
          docker push med3744lemin/demo-app:latest
